version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.3 # Specify a stable and valid version for Postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservice-net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6 # Updated to a valid version tag
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservice-net
    restart: unless-stopped

  mongodb:
    container_name: mongo
    image: mongo:6.0.4 # Confirmed stable MongoDB version
    environment:
      MONGO_INITDB_DATABASE: product-service
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo:/data/db # Fixed the MongoDB volume path
    ports:
      - "27017:27017"
    networks:
      - microservice-net
    restart: unless-stopped

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0 # Confirmed stable version
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME:-mongo}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD:-mongo}
      ME_CONFIG_MONGODB_SERVER: mongo # Connect to the "mongo" service
    ports:
      - "8081:8081"
    networks:
      - microservice-net
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev:1.1.0 # Confirmed stable version
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservice-net
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql:8.0.34 # Confirmed stable version
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: order-service


    networks:
      - microservice-net
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql


networks:
  microservice-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  mysql:
