
spring:
  data:
    mongodb:
      username: mongo
      password: mongo
      database: product-service
      host: localhost
      port: 27017
      authentication-database: admin
server:
  port: 9090